trigger: none
# - main
# - features/*

# pool: Stream line project agent

jobs:
  - job: installerjob
    pool: Agents_ka_jhund
    displayName: Terraform installer Job
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'
  
  - job: initvalidateplanjob
    pool: Agents_ka_jhund
    dependsOn: installerjob
    displayName: Init, Validate, Plan Job
    steps:
    - task: TerraformTask@5
      displayName: Terraform init task
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
        backendServiceArm: 'CI_CD_service'
        backendAzureRmStorageAccountName: 'rajatstg12'
        backendAzureRmContainerName: 'rajatcont1'
        backendAzureRmKey: 'terraform.tfstate'
      
    - task: TerraformTask@5
      displayName: Terraform Validate Task
      inputs:
        provider: 'azurerm'
        command: 'validate'
  
    - task: TerraformTask@5
      displayName: Terraform Plan Task
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'CI_CD_service'

  - job: ManualValidation
    displayName: Manual Validation Step
    dependsOn: initvalidateplanjob
    pool: server
    steps:
    - task: ManualValidation@1
      displayName: Manual Approval Before Apply
      inputs:
        instructions: 'Please review the Terraform plan and approve to continue.'
        notifyUsers: 'rajats12120@gmail.com'
        approvers: 'rajats12120@gmail.com'

  - job: initjobaftermanualvalidation
    displayName: Init & Apply After Manual Approval
    dependsOn: ManualValidation
    pool: Agents_ka_jhund
    steps:
    - task: TerraformTask@5
      displayName: Terraform init task
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'CI_CD_service'
        backendAzureRmStorageAccountName: 'rajatstg12'
        backendAzureRmContainerName: 'rajatcont1'
        backendAzureRmKey: 'terraform.tfstate'
 
 
    - task: TerraformTask@5
      displayName: Terraform Apply Task
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'CI_CD_service'