trigger: 
  branches:
   include:
     - main
     - features/*

pool: Agents_ka_jhund

jobs:
  - job: 
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

  - job: 
    steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'CICD_service'
          backendAzureRmResourceGroupName: 'rg1'
          backendAzureRmStorageAccountName: 'rajstg12'
          backendAzureRmContainerName: 'rajat-container'
          backendAzureRmKey: 'pankaj.tfstate'




