trigger: 
  branches:
   include:
     - main
     - features/*

pool: Agents_ka_jhund

jobs:
  - job: terraforminstall
    displayName: terraform installer
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

  - job: terraforminit
    displayName: terraform init
    steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'CICD_service'
          backendAzureRmResourceGroupName: 'rg1'
          backendAzureRmStorageAccountName: 'rajstg12'
          backendAzureRmContainerName: 'rajat-container'
          backendAzureRmKey: 'pankaj.tfstate'

  - job: terraformplan
    displayName: terraform plan
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: 'CICD_service'

        
      



