trigger: 
  branches:
   include:
     - main
     - features/*

pool: Agents_ka_jhund

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'CICD_service'
    backendAzureRmResourceGroupName: 'rg1'
    backendAzureRmStorageAccountName: 'rajstg12'
    backendAzureRmContainerName: 'rajat-container'
    backendAzureRmKey: 'pankaj.tfstate'


